//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34209
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace GXPEngine
{
	public class Button:Sprite
	{
		public Button (string filename,float buttonX,float buttonY):base(".../sprites/"+filename+"Button.png")
		{
			x = buttonX;
			y = buttonY;


		}
	}
}

