//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34209
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace GXPEngine
{
	class InstructionPage :Sprite
	{
		private MainMenu mainMenu;

		public InstructionPage (MainMenu _mainMenu):base (".../sprites/instructionPage.png")
		{
			mainMenu = _mainMenu;

		}

		public void Update(){
			if (Input.GetKeyDown (Key.Z)) {
				mainMenu.RemoveChild(this);
				this.Destroy();
			}

		}

	}
}

